import Foundation

/// Turns an assembled `TherapistReport` into readable Markdown.
///
/// The closing disclaimer at the bottom of `markdown(for:)` is not
/// decorative. It's the part of this whole feature that matters most:
/// once this file is exported, it can be opened, printed, or forwarded
/// completely outside this app, by someone who never saw any of the
/// in-app disclosures. The one place a compliance disclaimer is
/// guaranteed to travel with the data is inside the document itself.
struct TherapistReportRenderer: Sendable {

    func markdown(for report: TherapistReport) -> String {
        var lines: [String] = []

        lines.append("# Composure Wellness Summary")
        if let name = report.profileName {
            lines.append("**For:** \(name)")
        }
        lines.append("**Period:** \(report.config.dateRange.label)")
        lines.append("**Generated:** \(report.generatedAt.formatted(date: .abbreviated, time: .shortened))")
        if !report.config.providerContext.trimmingCharacters(in: .whitespaces).isEmpty {
            lines.append("**Note:** \(report.config.providerContext)")
        }
        lines.append("")

        if report.config.includedSections.contains(.overview) {
            lines.append(contentsOf: overviewSection(report))
        }
        if report.config.includedSections.contains(.stressTrends), !report.weeklyTrend.isEmpty {
            lines.append(contentsOf: trendSection(report))
        }
        if report.config.includedSections.contains(.sleep), let sleep = report.sleepAssociation {
            lines.append(contentsOf: sleepSection(sleep))
        }
        if report.config.includedSections.contains(.goals) {
            lines.append(contentsOf: goalsSection(report))
        }
        if report.config.includedSections.contains(.notes), !report.notes.isEmpty {
            lines.append(contentsOf: notesSection(report))
        }

        lines.append("---")
        lines.append(
            "_This is a personal wellness summary generated by the Composure app from the "
            + "person's own self-reported and camera-derived readings — not a clinical "
            + "assessment, diagnosis, or medical device output. Composure is not a HIPAA "
            + "covered entity or business associate; generating or sending this file carries "
            + "no compliance status of any kind. How this document is transmitted and stored "
            + "is the sender's and recipient's responsibility._"
        )

        return lines.joined(separator: "\n")
    }

    // MARK: - Sections

    private func overviewSection(_ report: TherapistReport) -> [String] {
        var lines = ["## Overview", "- Sessions recorded: \(report.sessionCount)"]
        if let average = report.averageStress {
            lines.append(String(format: "- Average stress reading: %.0f%%", average * 100))
        }
        if let peak = report.peakStress {
            lines.append(String(format: "- Peak stress reading: %.0f%%", peak * 100))
        }
        lines.append("")
        return lines
    }

    private func trendSection(_ report: TherapistReport) -> [String] {
        var lines = ["## Weekly stress trend"]
        for point in report.weeklyTrend {
            let weekLabel = point.weekStart.formatted(date: .abbreviated, time: .omitted)
            lines.append(
                String(
                    format: "- Week of %@: average %.0f%%, peak %.0f%%, %d session(s)",
                    weekLabel, point.averageStress * 100, point.peakStress * 100, point.sessionCount
                )
            )
        }
        lines.append("")
        return lines
    }

    private func sleepSection(_ sleep: SleepAssociation) -> [String] {
        var lines = ["## Sleep", "- \(sleep.headline)"]
        if let detail = sleep.detail {
            lines.append("- \(detail)")
        }
        lines.append("- _\(sleep.caveat)_")
        lines.append("")
        return lines
    }

    private func goalsSection(_ report: TherapistReport) -> [String] {
        [
            "## Consistency",
            "- Current streak: \(report.currentStreak) day(s)",
            "- Longest streak on record: \(report.bestStreakEver) day(s)",
            "- Guided breathing exercises completed: \(report.breathingSessionsCompleted)",
            ""
        ]
    }

    private func notesSection(_ report: TherapistReport) -> [String] {
        var lines = ["## Notes from this period"]
        for note in report.notes.sorted(by: { $0.date < $1.date }) {
            lines.append("**\(note.date.formatted(date: .abbreviated, time: .omitted)):** \(note.text)")
        }
        lines.append("")
        return lines
    }
}
